name:                fakedata
version:             0.2.2
github:              "psibi/fakedata"
license:             BSD3
author:              "Sibi Prabakaran"
maintainer:          "sibi@psibi.in"
copyright:           "Sibi Prabakaran"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- faker/lib/locales/*yml
- faker/lib/locales/en/*yml
- customFakeSource/en/*yml

# Metadata used when publishing your package
synopsis:            Library for producing fake data
category:            Random, Fake, FakeData

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psibi/fakedata#readme>

dependencies:
- base >= 4.7 && < 5
- random
- text
- exceptions
- vector
- yaml
- directory
- filepath
- containers
- template-haskell
- bytestring
- time

library:
  source-dirs: src

tests:
  fakedata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fakedata
    - hspec
    - vector
    - hspec-discover
    - time
